logging:
  version: 1
  formatters:
    standard:
      format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      formatter: standard
      level: INFO
    file:
      class: logging.FileHandler
      filename: logs/pipeline.log
      formatter: standard
      level: DEBUG
  root:
    handlers: [console, file]
    level: INFO

